[package]
name = "kiy4ku/robloxformatnumber"
version = "31.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = ["Blockzez"]
description = "Forked from FormatNumber by Blockzez."

[dependencies]
